name: bran
channels:
    - defaults
dependencies:
    - python=3.6.8
    - pip:
          - boto3>=1.9.104
          - botocore>=1.12.104
          - colorama>=0.3.9
          - boto>=2.49.0
          - pyinquirer>=1.0.3
          - pyperclip>=1.7.0
          - progress>=1.4